[buildpack]
name = "Ruby"
ruby_version = "2.5.5"

  [publish.Ignore]
  files = [
    "spec/"
  ]

  [[publish.Vendor]]
  # get tokens for logging build tokens
  url = "https://tuitu-buildpack.oss-cn-hangzhou.aliyuncs.com/ruby.tgz"
  dir = "."
  files = ["./.env"]
  [[publish.Vendor]]
  url = "https://cache.ruby-china.com/pub/ruby/ruby-2.5.5.tar.gz"
  dir = "vendor/ruby/cedar-14"
  [[publish.Vendor]]
  url = "https://cache.ruby-china.com/pub/ruby/ruby-2.5.5.tar.gz"
  dir = "vendor/ruby/heroku-16"
  [[publish.Vendor]]
  url = "https://cache.ruby-china.com/pub/ruby/ruby-2.5.5.tar.gz"
  dir = "vendor/ruby/heroku-18"
