[buildpack]
name = "Ruby"
ruby_version = "2.5.5"

  [publish.Ignore]
  files = [
    "spec/"
  ]

  [[publish.Vendor]]
  # get tokens for logging build tokens
  url = "https://tuitu-buildpack.oss-cn-hangzhou.aliyuncs.com/ruby.tgz"
  dir = "."
  files = ["./.env"]
  [[publish.Vendor]]
  url = "https://buildpack.tuitu-tech.cn/heroku-buildpack-ruby/cedar-14/ruby-2.5.5.tgz"
  dir = "vendor/ruby/cedar-14"
  [[publish.Vendor]]
  url = "https://buildpack.tuitu-tech.cn/heroku-buildpack-ruby/heroku-16/ruby-2.5.5.tgz"
  dir = "vendor/ruby/heroku-16"
  [[publish.Vendor]]
  url = "https://buildpack.tuitu-tech.cn/heroku-buildpack-ruby/heroku-18/ruby-2.5.5.tgz"
  dir = "vendor/ruby/heroku-18"
